[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/go-coap"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.4"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.21.0"

[prune]
  go-tests = true
  unused-packages = true
