[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/kit"

[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/go-coap"

[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/grpc-gateway"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.3.1"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "v1.2.1"

[prune]
  go-tests = true
  unused-packages = true
