[[override]]
  branch = "refcounter"
  name = "github.com/go-ocf/kit"

[[override]]
  branch = "dtls"
  name = "github.com/go-ocf/go-coap"

[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/grpc-gateway"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
